name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: fibonacci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB_URL: jdbc:postgresql://localhost:5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Maven Test
        run: mvn test
      - name: Maven Generate report
        run: mvn surefire-report:report
      - name: Execute Report Script
        run: ./././send-report.sh # Replace with the actual path to your script
        env:
          GITHUB_ACTIONS: true # Set this environment variable to indicate the script is running in GitHub Actions
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: fibonacci
          DB_USER: postgres
          DB_PASSWORD: postgres
          POSTGRES_DB_URL: jdbc:postgresql://localhost:5432
