name: push

on:
  workflow_run:
    workflows: ["Trigger Workflows"]  # Name of the first workflow
    types:
      - completed  # Trigger after the workflow completes
 

jobs:
  trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Trigger subsequent workflows
        run: echo "... starting..."
